// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace LogInApp.iOS
{
	public partial class RolrListViewController : UIView
	{
		public RolrListViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
