// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace LogInApp.iOS
{
	public partial class UserListViewController : UIView
	{
		public UserListViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
