// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace LogInApp.iOS
{
	public partial class ViewController2 : UIViewController
	{
		public ViewController2 (IntPtr handle) : base (handle)
		{
		}
	}
}
