#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LogInApp.Droid.Resource", IsApplication=true)]

namespace LogInApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int drawable_adduser = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int drawable_edituser = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int drawable_trashcan = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int drawable_usericon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_addrole = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_icon = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060009
			public const int List = 2131099657;
			
			// aapt resource value: 0x7f060015
			public const int addRole = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int addUser = 2131099668;
			
			// aapt resource value: 0x7f060001
			public const int addrole = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int adduser = 2131099655;
			
			// aapt resource value: 0x7f06000d
			public const int avatar = 2131099661;
			
			// aapt resource value: 0x7f060008
			public const int deleteuser = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int log_in = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int log_in_name = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int log_in_password = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int login = 2131099662;
			
			// aapt resource value: 0x7f060011
			public const int name = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int namesurname = 2131099663;
			
			// aapt resource value: 0x7f060000
			public const int newrolename = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int newuserlogin = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int newusername = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int newuserpassword = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int newuserrole = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int newusersurname = 2131099651;
			
			// aapt resource value: 0x7f060016
			public const int surname = 2131099670;
			
			// aapt resource value: 0x7f060013
			public const int toolmenu = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int trashcan = 2131099666;
			
			// aapt resource value: 0x7f060010
			public const int userrole = 2131099664;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_addnewrole = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int activity_addnewuser = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int activity_list = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int activity_listitem = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int activity_login = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int activity_profileitem = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int activity_rolelistitem = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int activity_toolbar = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int activity_userlistitem = 2130968584;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int drawable_addrole = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int drawable_adduser = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int drawable_edituser = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int drawable_trashcan = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int drawable_usericon = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Icon = 2130903045;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f05000d
			public const int DBString = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int addrole = 2131034123;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int log_in = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int log_in_name = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int log_in_password = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int newuser = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int rolename = 2131034124;
			
			// aapt resource value: 0x7f050008
			public const int userlogin = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int username = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int userpassword = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int userrole = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int usersurname = 2131034118;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
