// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace LogInApp.iOS
{
	public partial class MainMenuViewController : UITabBarController
	{
		public MainMenuViewController (IntPtr handle) : base (handle)
		{
            
		}
	}
}
